### PR TITLE
[TECHNICAL REQUEST] LPS-61137 Permission denied error in IE when you embed Liferay content into external html page

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi,

Could you review it, please?

There was an other similar issue (LPS-16654) in the past with IE which was fixed by empty catch. And there is really nothing else what we can do, because IE does not allow javascript to read from parent's window's location.

If you allow me I could create an SDH.

Thank you in advance
Péter

### CODE REVIEW

**Comment by zsagia** [comment]
@peterborkuti 

Hi Peter,

My question is: Why don't you put "parentThemeDisplay = parentWindow.themeDisplay;" to the previous try block?

We could use one try catch block instead of two.

**Comment by peterborkuti** [comment]
Because I did not like to change the logic. This seemed to me the less error-prone.
But, as for the SDH, it is urgent. If it is your only concern, may I issue the fix?

**Comment by zsagia** [comment]
Right.


Zsolt Szabo a.k.a. Zsaga

Engineer, Technical Support

Subscription Services | EMEA

Liferay Hungary | Madarász Viktor u. 47., 1138, Budapest, Hungary

**Comment by zsagia** [comment]
https://github.com/blzaugg/liferay-portal/pull/161

**Pull request closed without merging**
