### PR TITLE
LPS-57607

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @zsagia,

Attached is an update for http://issues.liferay.com/browse/LPS-57607. I made some changes to this pull request that you can test to make sure it works as intended.

I also had a question regarding https://github.com/jonmak08/liferay-portal/blob/75c1bc794c7afdc7755c6357abd777a191799103/portal-web/docroot/html/taglib/ui/input_date/page.jsp#L116...L139.  I understand the ```if/else``` block, but do not quite see how it will ever get into the ```else``` block since we are not initializing the ```Liferay.component()``` anywhere else.  If we create the ```Liferay.component()``` in another file, the calls here will work, but I just do not see where that would be possible given the ```namespace``` and ```name```.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by zsagia** [comment]
Hi @jonmak08,

The answer for your question is that I wanted to use only one FormValidator instance to all input date instances. Thus I needed to merge old rules object with new one.
In this case, I saw that you used FormValidator instance with namespace, it is unnecessary. You can delete else block.

Thanks again,
 Zsaga

**Comment by jonmak08** [comment]
Hey @zsagia,

If we merged all the rules for the input date together, then all input date instances would use the same rules.

Say for instance you have a form where you have 2 input dates.  One input date is for your birthday (so it can be any date).  Then later on the page you have another input date for listing your child's birthday, but you want to make sure your child is under 18.  You would need to add a custom rule for this child's birthday but not your birthday input date.

In that scenario, you would need 2 separate form validator rules for the 2 input dates because each one requires something specific.  I think that would be a case where we would not want to merge the rules together.

Is that correct?

Thanks!

**Comment by blzaugg** [comment]
https://github.com/jonmak08/liferay-portal/pull/1332

**Comment by jonmak08** [comment]
Closing this pull request in favor of https://github.com/jonmak08/liferay-portal/pull/1332

**Pull request closed without merging**
